# Generated by Django 6.0.4 on 2026-05-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('search', 'Search History'), ('ads', 'Ad Link History'), ('mention', 'Mention History'), ('account', 'Account History'), ('reuse', 'Content Reuse'), ('deleted', 'Recently Deleted')], max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
