# Generated by Django 6.0.4 on 2026-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField()),
                ('category', models.CharField(choices=[('trending', 'Trending'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('islamic', 'Islamic'), ('sports', 'Sports'), ('food', 'Food'), ('music', 'Music'), ('other', 'Other')], default='other', max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('user_img', models.URLField(blank=True)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
