# Generated by Django 6.0.4 on 2026-05-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_postview_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('initials', models.CharField(blank=True, max_length=5)),
                ('color', models.CharField(default='gray', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=20)),
                ('joined', models.CharField(blank=True, max_length=50)),
                ('posts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('doc', 'Document')], default='doc', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('img', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('kept', 'Kept'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
