# Generated by Django 6.0.4 on 2026-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_adminuser_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('new_followers', models.IntegerField(default=0)),
                ('engage_rate', models.FloatField(default=0.0)),
                ('weekly_growth', models.FloatField(default=0.0)),
                ('performance', models.FloatField(default=0.0)),
                ('mon', models.IntegerField(default=0)),
                ('tue', models.IntegerField(default=0)),
                ('wed', models.IntegerField(default=0)),
                ('thu', models.IntegerField(default=0)),
                ('fri', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
