# Generated by Django 6.0.4 on 2026-05-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('from_name', models.CharField(max_length=100)),
                ('from_img', models.CharField(blank=True, max_length=500)),
                ('type', models.CharField(choices=[('Follow', 'Follow'), ('Likes', 'Likes'), ('Comments', 'Comments')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
