# Generated by Django 6.0.4 on 2026-06-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_remove_user_fcm_token_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.FloatField(help_text='Size in MB')),
                ('file_type', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='video', max_length=10)),
                ('caption', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. 0:42 min', max_length=20)),
                ('resolution', models.CharField(blank=True, help_text='e.g. 1920x1080', max_length=50)),
                ('file_url', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userpost',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homefeedpost',
            name='media_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='video_url',
            field=models.CharField(max_length=1000),
        ),
    ]
