# Generated by Django 6.0.4 on 2026-06-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_reelupload_userpost_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField()),
                ('following_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower_id', 'following_id')},
            },
        ),
    ]
