# Generated by Django 6.0.4 on 2026-06-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_userfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.IntegerField()),
                ('request_body', models.TextField(blank=True)),
                ('response_body', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('duration_ms', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
